version: "2"
services:
  db:
    image: mysql/mysql-server:5.6
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql/fineract:/var/lib/mysql
      - ./initdb.d/mifosplatform.sql:/docker-entrypoint-initdb.d/mifosplatform.sql
